### ISSUE TITLE
Login Form - Password Input Does Not Accept Paste

### ISSUE THREAD

**Issue by N3X15** [Take-Over-Games/LavenderVR#12]
The login form when starting Lavender VR does not accept pasting in the login form.  This presents a challenge for those of us with complex and/or long passwords stored in a password manager.

## Version
Content build ID 4706959 (Nightly)

## Reproduction steps
1. Open Lavender in Desktop mode
1. Fill in username (Paste works here)
1. Attempt to paste in password with CTRL+V

## Expected behaviour
* Password is pasted into the input and hidden

## Observed behaviour
* Input remains blank.

**Comment by june-tog** [comment]
Migration from CEF to new UI framework indirectly fixes this.
